project:
  type: website
  output-dir: _site
  render:
    - project.qmd
    - poster.qmd
    - prototypes.qmd
    - theme1.qmd
    - theme2.qmd
    - theme3.qmd
    - conclusion
    - user_guide.qmd
    - about.qmd

website:
  title: "IS428 Project - Team PowerPuffs"
  navbar:
    left:
      - href: project.qmd
        text: "Project Proposal"
#      - text: "Methodology"
 #       menu:
        # this is for the hamburger
      - href: poster.qmd
        text: "Poster"
      - href: prototypes.qmd
        text: "Data Exploration & Visualisation Prototypes"
      - text: "Analysis & Results"
        menu: 
        - theme1.qmd
        - theme2.qmd
        - theme3.qmd
        - conclusion.qmd
      - href: user_guide.qmd
        text: "User Guide"
    right:
      - href: about.qmd
        text: "About"

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual