project:
  type: website
  output-dir: _site
  render:
    - project.qmd
    - poster.qmd
    - prototypes.qmd
    - analysis_results.qmd
    - user_guide.qmd
    - about.qmd

website:
  title: "IS428 Project - Team PowerPuffs"
  navbar:
    left:
      - href: project.qmd
        text: "Project Proposal"
#      - text: "Methodology"
 #       menu:
        # this is for the hamburger
      - href: poster.qmd
        text: "Poster"
      - href: prototypes.qmd
        text: "Data Exploration & Visualisation Prototypes"
      - href: analysis_results.qmd
        text: "Analysis & Results"
      - href: user_guide.qmd
        text: "User Guide"
    right:
      - href: about.qmd
        text: "About"

format:
  html:
    theme: minty
    css: styles.css
    toc: true

editor: visual